# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S3STUkFTcnFeU8773Ld1KDd0c_dLMH3a
"""

import streamlit as st
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.patches import FancyBboxPatch
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import yfinance as yf
import datetime, warnings
from zoneinfo import ZoneInfo

warnings.filterwarnings("ignore")
st.set_page_config(page_title="◈ Global Finance Dashboard",
                   layout="wide", page_icon="📊",
                   initial_sidebar_state="collapsed")

NY = ZoneInfo("America/New_York")
def ny_now(): return datetime.datetime.now(NY)

C = dict(bg="#000000", panel="#0D0D0D", orange="#FF6600",
         yellow="#FFD700", green="#00FF41", red="#FF3333",
         blue="#00BFFF", gray="#777777", white="#FFFFFF")

GLOBAL_INDICES = {
    "🇺🇸 UNITED STATES": {"S&P 500":"^GSPC","NASDAQ":"^IXIC","Dow Jones":"^DJI","Russell 2K":"^RUT","VIX":"^VIX"},
    "🇪🇺 EUROPE":         {"FTSE 100":"^FTSE","DAX":"^GDAXI","CAC 40":"^FCHI","Euro Stoxx 50":"^STOXX50E","IBEX 35":"^IBEX","AEX":"^AEX"},
    "🌏 ASIA-PACIFIC":    {"Nikkei 225":"^N225","Hang Seng":"^HSI","ASX 200":"^AXJO","Shanghai":"000001.SS","KOSPI":"^KS11","TAIEX":"^TWII"},
    "🌎 AMERICAS":        {"Bovespa":"^BVSP","IPC Mexico":"^MXX","TSX Canada":"^GSPTSE","Merval":"^MERV"}
}
FOREX_MAJOR = {"EUR/USD":"EURUSD=X","GBP/USD":"GBPUSD=X","USD/JPY":"USDJPY=X","USD/CHF":"USDCHF=X","AUD/USD":"AUDUSD=X","USD/CAD":"USDCAD=X","NZD/USD":"NZDUSD=X"}
FOREX_EM    = {"USD/BRL":"USDBRL=X","USD/MXN":"USDMXN=X","USD/CNH":"USDCNH=X","USD/INR":"USDINR=X","USD/ZAR":"USDZAR=X","USD/TRY":"USDTRY=X","USD/KRW":"USDKRW=X","USD/ARS":"USDARS=X"}
COMMODITIES = {
    "⚡ ENERGY":     {"WTI Crude":"CL=F","Brent Crude":"BZ=F","Natural Gas":"NG=F","Gasoline":"RB=F","Heating Oil":"HO=F"},
    "🥇 METALS":     {"Gold":"GC=F","Silver":"SI=F","Copper":"HG=F","Platinum":"PL=F","Palladium":"PA=F"},
    "🌾 AGRICULTURE":{"Corn":"ZC=F","Wheat":"ZW=F","Soybeans":"ZS=F","Coffee":"KC=F","Sugar":"SB=F","Cotton":"CT=F"}
}
CRYPTO = {"₿ CRYPTO":{"Bitcoin":"BTC-USD","Ethereum":"ETH-USD","BNB":"BNB-USD","Solana":"SOL-USD","XRP":"XRP-USD","Cardano":"ADA-USD","Dogecoin":"DOGE-USD","Avalanche":"AVAX-USD","Polkadot":"DOT-USD","Chainlink":"LINK-USD"}}
SECTORS       = {"XLK":"Tech","XLF":"Financials","XLV":"Healthcare","XLE":"Energy","XLI":"Industrials","XLY":"Cons. Disc.","XLP":"Cons. Stap","XLRE":"Real Est.","XLB":"Materials","XLU":"Utilities","XLC":"Comm. Svcs"}
YIELD_TICKERS = {"3M":"^IRX","5Y":"^FVX","10Y":"^TNX","30Y":"^TYX"}

# ── CSS THEME ─────────────────────────────────────────────────
st.markdown("""
<style>
  body, .stApp { background-color: #000000 !important; color: #FFFFFF; }
  .stTabs [data-baseweb="tab-list"] { background: #000; border-bottom: 2px solid #FF6600; gap: 4px; }
  .stTabs [data-baseweb="tab"] { background: #0D0D0D; color: #FF6600; border: 1px solid #FF6600;
                                   border-radius: 4px 4px 0 0; font-family: monospace; font-weight: bold; }
  .stTabs [aria-selected="true"] { background: #FF6600 !important; color: #000 !important; }
  .stButton > button { background: #FF6600; color: #000; font-family: monospace;
                        font-weight: bold; border: none; border-radius: 4px; }
  .stButton > button:hover { background: #FFD700; color: #000; }
  .stSelectbox select, .stTextInput input { background: #0D0D0D; color: #FFD700;
                                             border: 1px solid #FF6600; font-family: monospace; }
  div[data-testid="stMetricValue"] { color: #FFD700 !important; font-family: monospace; font-size: 1.4rem; }
  div[data-testid="stMetricLabel"] { color: #FF6600 !important; font-family: monospace; }
  div[data-testid="stMetricDelta"] { font-family: monospace; }
  h1, h2, h3 { color: #FF6600 !important; font-family: monospace !important; }
  .stMarkdown { font-family: monospace; }
  .header-box { background:#000; font-family:Courier New,monospace; padding:14px 20px;
                 border-bottom:3px solid #FF6600; display:flex; justify-content:space-between;
                 align-items:center; margin-bottom:16px; }
  .metric-card { background:#0D0D0D; border:1px solid #333; border-radius:6px;
                  padding:12px 16px; text-align:center; }
</style>""", unsafe_allow_html=True)

# ── DATA HELPERS ─────────────────────────────────────────────
def _close(raw, tk=None):
    if isinstance(raw.columns, pd.MultiIndex):
        sub = raw["Close"]
        if tk and tk in sub.columns: return sub[tk].dropna()
        return sub.dropna()
    return raw["Close"].dropna()

@st.cache_data(ttl=300)
def batch_quotes(tickers_tuple, period="5d"):
    tickers = list(tickers_tuple)
    result = {t: dict(price=0.0, chg=0.0, pct=0.0) for t in tickers}
    if not tickers: return result
    try:
        raw = yf.download(tickers, period=period, auto_adjust=True, progress=False)
        for tk in tickers:
            try:
                s = _close(raw, tk) if len(tickers) > 1 else _close(raw)
                if len(s) < 2: continue
                price = float(s.iloc[-1]); prev = float(s.iloc[-2])
                chg = price - prev; pct = chg / prev * 100 if prev else 0.0
                result[tk] = dict(price=price, chg=chg, pct=pct)
            except: pass
    except: pass
    return result

@st.cache_data(ttl=300)
def fetch_ohlcv(ticker, period="6mo"):
    try:
        df = yf.download(ticker, period=period, auto_adjust=True, progress=False)
        if isinstance(df.columns, pd.MultiIndex): df.columns = df.columns.get_level_values(0)
        return df[df["Close"].notna()].copy()
    except: return pd.DataFrame()

def rsi(c, w=14):
    d = c.diff(); g = d.clip(lower=0).rolling(w).mean(); l = (-d.clip(upper=0)).rolling(w).mean()
    return 100 - 100 / (1 + g / l.replace(0, np.nan))

def macd(c, f=12, s=26, sig=9):
    m = c.ewm(span=f, min_periods=1).mean() - c.ewm(span=s, min_periods=1).mean()
    sg = m.ewm(span=sig, min_periods=1).mean()
    return m, sg, m - sg

def bbands(c, w=20):
    mid = c.rolling(w, min_periods=1).mean(); std = c.rolling(w, min_periods=1).std()
    return mid + 2*std, mid, mid - 2*std

def fmt_price(p):
    if p > 10000: return f"{p:,.0f}"
    elif p > 100: return f"{p:,.2f}"
    elif p > 1:   return f"{p:.4f}"
    elif p > 0:   return f"{p:.6f}"
    return "—"

def fmt_chg(chg):
    a = abs(chg)
    if a > 100:   return f"{a:,.2f}"
    elif a > 0.1: return f"{a:.4f}"
    return f"{a:.6f}"

# ── HTML TABLE BUILDER ───────────────────────────────────────
def html_table(title, sections, icon="◈"):
    all_tickers = [tk for sec in sections.values() for tk in sec.values()]
    quotes = batch_quotes(tuple(all_tickers))
    now    = ny_now().strftime("%I:%M %p ET")
    rows   = ""
    for sec_name, items in sections.items():
        rows += f"<tr><td colspan='5' style='background:#111122;color:#FF6600;font-weight:bold;padding:7px 14px;font-size:11px;letter-spacing:2px;border-top:1px solid #222'>{sec_name}</td></tr>"
        for name, tk in items.items():
            q = quotes.get(tk, dict(price=0, chg=0, pct=0))
            p = q["price"]; chg = q["chg"]; pct = q["pct"]
            col = "#00FF41" if chg >= 0 else "#FF3333"
            sign = "▲" if chg >= 0 else "▼"
            rows += (f"<tr style='border-bottom:1px solid #111'>"
                     f"<td style='color:#FFD700;font-weight:bold;padding:7px 14px'>{name}</td>"
                     f"<td style='color:white;padding:7px 14px'>{fmt_price(p)}</td>"
                     f"<td style='color:{col};padding:7px 14px'>{sign} {fmt_chg(chg)}</td>"
                     f"<td style='color:{col};padding:7px 14px'>{pct:+.2f}%</td>"
                     f"<td style='color:#444;padding:7px 14px;font-size:10px'>{tk}</td></tr>")
    hdr = "".join(f"<th style='color:#FF6600;text-align:left;padding:6px 14px'>{h}</th>"
                  for h in ["NAME","PRICE","CHANGE","CHG%","TICKER"])
    return f"""
    <div style='background:#000;font-family:Courier New,monospace;padding:14px;border:1px solid #FF6600;border-radius:4px'>
      <div style='color:#FF6600;font-size:13px;font-weight:bold;border-bottom:1px solid #333;
                  padding-bottom:8px;margin-bottom:10px;display:flex;justify-content:space-between'>
        <span>{icon} {title}</span><span style='color:#555;font-size:11px'>{now}</span>
      </div>
      <table style='width:100%;border-collapse:collapse'>
        <thead><tr style='border-bottom:2px solid #FF6600'>{hdr}</tr></thead>
        <tbody>{rows}</tbody>
      </table>
    </div>"""

# ── GLOBAL MARKETS FIGURE ────────────────────────────────────
@st.cache_data(ttl=300)
def build_global_fig():
    all_tks = tuple(tk for reg in GLOBAL_INDICES.values() for tk in reg.values())
    quotes  = batch_quotes(all_tks)
    fig = plt.figure(figsize=(16, 10), facecolor=C["bg"])
    gs  = gridspec.GridSpec(2, 2, figure=fig, hspace=0.52, wspace=0.3)
    region_colors = [C["blue"], "#8888ff", C["orange"], "#ffaa00"]
    for panel_idx, ((reg_name, reg_items), reg_col) in enumerate(zip(GLOBAL_INDICES.items(), region_colors)):
        ax = fig.add_subplot(gs[panel_idx // 2, panel_idx % 2])
        ax.set_facecolor(C["bg"]); ax.axis("off")
        ax.set_title(f"  {reg_name}", color=reg_col, fontsize=11, fontweight="bold", fontfamily="monospace", loc="left", pad=8)
        items = list(reg_items.items()); n = len(items)
        cols_n = min(3, n); rows_n = (n + cols_n - 1) // cols_n
        bw = 1 / cols_n - 0.03; bh = 0.78 / rows_n - 0.04
        for i, (name, tk) in enumerate(items):
            q = quotes.get(tk, dict(price=0, chg=0, pct=0))
            r = i // cols_n; c_i = i % cols_n
            bx = c_i / cols_n + 0.01; by = 0.92 - (r + 1) * (bh + 0.04)
            col = C["green"] if q["chg"] >= 0 else C["red"]
            ax.add_patch(FancyBboxPatch((bx, by), bw, bh, boxstyle="round,pad=0.01",
                facecolor="#0D0D0D", edgecolor=col, linewidth=1.1, transform=ax.transAxes))
            cx = bx + bw / 2; cy = by + bh / 2
            p_str = fmt_price(q["price"])
            sign  = "▲" if q["chg"] >= 0 else "▼"
            ax.text(cx, cy + bh*0.26, name,   ha="center", color=reg_col, fontsize=7,  fontweight="bold", fontfamily="monospace", transform=ax.transAxes)
            ax.text(cx, cy,           p_str,  ha="center", color=C["yellow"], fontsize=9.5, fontweight="bold", fontfamily="monospace", transform=ax.transAxes)
            ax.text(cx, cy - bh*0.28, f"{sign} {q['pct']:+.2f}%", ha="center", color=col, fontsize=7, fontfamily="monospace", transform=ax.transAxes)
    plt.suptitle("◈  GLOBAL EQUITY MARKETS", color=C["orange"], fontsize=14, fontweight="bold", fontfamily="monospace", y=0.99)
    plt.tight_layout(pad=1.5, rect=[0, 0, 1, 0.97])
    return fig

# ── CHART FIGURE ─────────────────────────────────────────────
@st.cache_data(ttl=300)
def build_chart_fig(ticker="SPY", period="6mo"):
    df = fetch_ohlcv(ticker, period)
    if df.empty or len(df) < 2:
        fig = go.Figure()
        fig.add_annotation(text=f"❌ No data for {ticker}", xref="paper", yref="paper",
                           x=0.5, y=0.5, showarrow=False,
                           font=dict(color="#FF3333", size=14, family="Courier New"))
        fig.update_layout(template="plotly_dark", paper_bgcolor="#000", plot_bgcolor="#0D0D0D")
        return fig
    c = df["Close"]
    df["RSI"] = rsi(c)
    df["MACD"], df["Sig"], df["H"] = macd(c)
    df["BB_up"], df["BB_mid"], df["BB_lo"] = bbands(c)
    df["EMA20"] = c.ewm(span=20, min_periods=1).mean()
    df["EMA50"] = c.ewm(span=50, min_periods=1).mean()
    df = df[df["Close"].notna() & df["Open"].notna()].copy()
    last = float(df["Close"].iloc[-1]); prev = float(df["Close"].iloc[-2])
    chg  = last - prev; pct = chg / prev * 100 if prev else 0
    col_t = C["green"] if chg >= 0 else C["red"]
    sign  = "▲" if chg >= 0 else "▼"
    fig   = make_subplots(rows=4, cols=1, shared_xaxes=True,
                          row_heights=[0.50, 0.15, 0.18, 0.17], vertical_spacing=0.02)
    fig.add_trace(go.Candlestick(x=df.index, open=df["Open"], high=df["High"],
                                  low=df["Low"], close=df["Close"],
                                  increasing_line_color=C["green"],
                                  decreasing_line_color=C["red"], name=ticker), row=1, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df["BB_up"], line=dict(color="rgba(150,150,255,0.5)", width=1, dash="dash"), showlegend=False), row=1, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df["BB_lo"], line=dict(color="rgba(150,150,255,0.5)", width=1, dash="dash"), fill="tonexty", fillcolor="rgba(100,100,255,0.05)", showlegend=False), row=1, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df["EMA20"], line=dict(color=C["yellow"], width=1.2), name="EMA20"), row=1, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df["EMA50"], line=dict(color=C["blue"],   width=1.2), name="EMA50"), row=1, col=1)
    vcols = [C["green"] if float(cl) >= float(op) else C["red"] for cl, op in zip(df["Close"], df["Open"])]
    fig.add_trace(go.Bar(x=df.index, y=df["Volume"], marker_color=vcols, showlegend=False, opacity=0.7), row=2, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df["RSI"], line=dict(color=C["blue"], width=1.2), showlegend=False), row=3, col=1)
    fig.add_hline(y=70, line=dict(color=C["red"],   dash="dash", width=0.8), row=3, col=1)
    fig.add_hline(y=30, line=dict(color=C["green"], dash="dash", width=0.8), row=3, col=1)
    hcols = [C["green"] if v >= 0 else C["red"] for v in df["H"]]
    fig.add_trace(go.Bar(x=df.index, y=df["H"], marker_color=hcols, showlegend=False, opacity=0.7), row=4, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df["MACD"], line=dict(color=C["blue"],   width=1.2), name="MACD"),   row=4, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df["Sig"],  line=dict(color=C["orange"], width=1.2), name="Signal"), row=4, col=1)
    fig.update_layout(
        template="plotly_dark", paper_bgcolor="#000", plot_bgcolor="#0D0D0D",
        title=dict(text=(f"<b style='color:{C['orange']}'>{ticker.upper()}</b>  "
                         f"<span style='color:{col_t}'>{fmt_price(last)} {sign} {fmt_chg(chg)} ({pct:+.2f}%)</span>"),
                   font=dict(family="Courier New", size=14), x=0),
        height=680, xaxis_rangeslider_visible=False,
        legend=dict(orientation="h", x=0, y=1.02, bgcolor="rgba(0,0,0,0.5)",
                    font=dict(family="Courier New", size=9)),
        font=dict(family="Courier New", color=C["gray"]),
        margin=dict(l=50, r=20, t=55, b=20))
    fig.update_xaxes(gridcolor="#1a1a1a")
    fig.update_yaxes(gridcolor="#1a1a1a")
    return fig

# ── MACRO FIGURE ─────────────────────────────────────────────
@st.cache_data(ttl=300)
def build_macro_fig():
    fig = plt.figure(figsize=(16, 10), facecolor=C["bg"])
    gs  = gridspec.GridSpec(2, 3, figure=fig, hspace=0.5, wspace=0.35)
    ax_vix = fig.add_subplot(gs[0, :2]); ax_vix.set_facecolor("#0D0D0D")
    try:
        vd = yf.download("^VIX", period="1y", auto_adjust=True, progress=False)
        cv = _close(vd).dropna(); lv = float(cv.iloc[-1])
        cv_col = C["green"] if lv < 20 else C["red"]
        ax_vix.plot(vd.index[-len(cv):], cv, color=C["orange"], linewidth=1.4)
        ax_vix.fill_between(vd.index[-len(cv):], cv, float(cv.min()), alpha=0.15, color=C["orange"])
        ax_vix.axhline(20, color=C["red"],   lw=0.8, ls="--", alpha=0.6, label="Fear (>20)")
        ax_vix.axhline(12, color=C["green"], lw=0.8, ls="--", alpha=0.6, label="Greed (<12)")
        ax_vix.fill_between(vd.index[-len(cv):], 0,  12,  alpha=0.06, color=C["green"])
        ax_vix.fill_between(vd.index[-len(cv):], 20, 100, alpha=0.06, color=C["red"])
        ax_vix.text(0.99, 0.93, f"VIX: {lv:.2f}", transform=ax_vix.transAxes,
                    ha="right", va="top", color=cv_col, fontsize=13, fontweight="bold", fontfamily="monospace")
    except: pass
    ax_vix.set_title("  VIX — VOLATILITY / FEAR INDEX (1Y)", color=C["orange"],
                     fontsize=11, fontweight="bold", fontfamily="monospace", loc="left")
    ax_vix.tick_params(colors=C["gray"], labelsize=7)
    ax_vix.legend(facecolor="#111", edgecolor="#333", labelcolor=C["white"], fontsize=7)
    ax_vix.grid(alpha=0.1, color=C["gray"])
    for sp in ax_vix.spines.values(): sp.set_edgecolor("#333333")

    ax_yc = fig.add_subplot(gs[0, 2]); ax_yc.set_facecolor("#0D0D0D")
    tks_y = list(YIELD_TICKERS.values()); lbls_y = list(YIELD_TICKERS.keys()); mat_x = [0.25, 5, 10, 30]
    try:
        ry = yf.download(tks_y, period="1y", auto_adjust=True, progress=False)
        def get_yc(idx):
            vals = []
            for tk in tks_y:
                try:    vals.append(float(_close(ry, tk).iloc[idx]))
                except: vals.append(None)
            return vals
        def yc_plot(vals, lbl, col, sty="-"):
            pts = [(x, v) for x, v in zip(mat_x, vals) if v and v > 0]
            if not pts: return
            xs, ys = zip(*pts)
            ax_yc.plot(xs, ys, f"o{sty}", color=col, linewidth=2, markersize=6, label=lbl, alpha=0.9)
            if sty == "-":
                ax_yc.fill_between(xs, ys, alpha=0.1, color=col)
                for x, y, lb in zip(xs, ys, lbls_y):
                    ax_yc.annotate(f"{lb}\n{y:.2f}%", xy=(x, y), xytext=(0, 12),
                                   textcoords="offset points", ha="center", fontsize=7,
                                   color=C["yellow"], fontfamily="monospace")
        yc_plot(get_yc(-1), "Today",  C["orange"], "-")
        yc_plot(get_yc(0),  "1Y Ago", C["gray"],   "--")
    except: pass
    ax_yc.set_xticks(mat_x); ax_yc.set_xticklabels(lbls_y, color=C["gray"], fontsize=7)
    ax_yc.set_title("  US YIELD CURVE", color=C["orange"], fontsize=10,
                    fontweight="bold", fontfamily="monospace", loc="left")
    ax_yc.tick_params(colors=C["gray"], labelsize=7)
    ax_yc.legend(facecolor="#111", edgecolor="#333", labelcolor=C["white"], fontsize=7)
    ax_yc.grid(alpha=0.1, color=C["gray"])
    for sp in ax_yc.spines.values(): sp.set_edgecolor("#333333")

    ax_sec = fig.add_subplot(gs[1, :2]); ax_sec.set_facecolor("#0D0D0D")
    sec_q   = batch_quotes(tuple(SECTORS.keys()))
    slabels = list(SECTORS.values())
    svalues = [sec_q.get(tk, dict(pct=0))["pct"] for tk in SECTORS]
    scolors = [C["green"] if v >= 0 else C["red"] for v in svalues]
    sbars   = ax_sec.barh(slabels, svalues, color=scolors, height=0.6, edgecolor="#222")
    ax_sec.axvline(0, color=C["gray"], linewidth=0.8, linestyle="--")
    ax_sec.set_title("  S&P 500 SECTOR ROTATION", color=C["orange"], fontsize=10,
                     fontweight="bold", fontfamily="monospace", loc="left")
    ax_sec.tick_params(colors=C["white"], labelsize=8)
    for sp in ax_sec.spines.values(): sp.set_edgecolor("#333333")
    for bar, val in zip(sbars, svalues):
        ax_sec.text(val + (0.02 if val >= 0 else -0.02), bar.get_y() + bar.get_height()/2,
                    f"{val:+.2f}%", va="center", ha="left" if val >= 0 else "right",
                    color=C["white"], fontsize=7.5, fontfamily="monospace")

    ax_snap = fig.add_subplot(gs[1, 2]); ax_snap.set_facecolor("#0D0D0D"); ax_snap.axis("off")
    ax_snap.set_title("  KEY ASSETS SNAPSHOT", color=C["orange"], fontsize=10,
                      fontweight="bold", fontfamily="monospace", loc="left")
    snap = {"Gold":"GC=F","WTI Oil":"CL=F","BTC":"BTC-USD","EUR/USD":"EURUSD=X",
            "10Y Yield":"^TNX","Silver":"SI=F","Copper":"HG=F","Nat. Gas":"NG=F"}
    snap_q = batch_quotes(tuple(snap.values()))
    y_p = 0.88
    for name, tk in snap.items():
        q = snap_q.get(tk, dict(price=0, chg=0, pct=0))
        col  = C["green"] if q["chg"] >= 0 else C["red"]
        sign = "▲" if q["chg"] >= 0 else "▼"
        ax_snap.text(0.02, y_p, name,                  transform=ax_snap.transAxes, color=C["orange"], fontsize=8.5, fontfamily="monospace", fontweight="bold")
        ax_snap.text(0.50, y_p, fmt_price(q["price"]), transform=ax_snap.transAxes, color=C["yellow"], fontsize=8.5, fontfamily="monospace")
        ax_snap.text(0.80, y_p, f"{sign}{abs(q['pct']):.2f}%", transform=ax_snap.transAxes, color=col, fontsize=8.5, fontfamily="monospace")
        y_p -= 0.11
    plt.suptitle("◈  MACRO DASHBOARD", color=C["orange"], fontsize=14,
                 fontweight="bold", fontfamily="monospace", y=0.99)
    plt.tight_layout(pad=1.5, rect=[0, 0, 1, 0.97])
    return fig

# ── NEWS ─────────────────────────────────────────────────────
@st.cache_data(ttl=180)
def get_news(ticker):
    try: return yf.Ticker(ticker).news[:20] or []
    except: return []

# ════════════════════════════════════════════════════════════
#  🚀  MAIN STREAMLIT APP
# ════════════════════════════════════════════════════════════
now_str = ny_now().strftime("%A, %B %d %Y  |  %I:%M %p ET")
st.markdown(f"""
<div class='header-box'>
  <span style='color:#FF6600;font-size:22px;font-weight:bold;letter-spacing:3px'>◈ GLOBAL FINANCE DASHBOARD</span>
  <span style='color:#FFD700;font-size:12px'>{now_str}</span>
  <span style='color:#00FF41;font-size:12px'>● LIVE  |  Yahoo Finance</span>
</div>""", unsafe_allow_html=True)

tab1, tab2, tab3, tab4, tab5, tab6, tab7 = st.tabs(
    ["🌍 GLOBAL", "💱 FOREX", "🛢 COMMODITIES", "₿ CRYPTO", "📊 CHART", "📉 MACRO", "📰 NEWS"])

# ── TAB 1: GLOBAL ────────────────────────────────────────────
with tab1:
    col_r, col_ref = st.columns([8, 1])
    with col_ref:
        if st.button("🔄 Refresh", key="ref_global"): st.cache_data.clear()
    with st.spinner("Loading global markets..."):
        fig = build_global_fig()
        st.pyplot(fig, use_container_width=True)
        plt.close(fig)

# ── TAB 2: FOREX ─────────────────────────────────────────────
with tab2:
    if st.button("🔄 Refresh", key="ref_forex"): st.cache_data.clear()
    with st.spinner("Fetching forex..."):
        st.markdown(html_table("FOREX — CURRENCY MARKETS",
                               {"💵 MAJOR PAIRS": FOREX_MAJOR,
                                "🌐 EMERGING MARKETS": FOREX_EM}, "💱"),
                    unsafe_allow_html=True)

# ── TAB 3: COMMODITIES ───────────────────────────────────────
with tab3:
    if st.button("🔄 Refresh", key="ref_cmd"): st.cache_data.clear()
    with st.spinner("Fetching commodities..."):
        st.markdown(html_table("GLOBAL COMMODITIES", COMMODITIES, "🛢"),
                    unsafe_allow_html=True)

# ── TAB 4: CRYPTO ────────────────────────────────────────────
with tab4:
    if st.button("🔄 Refresh", key="ref_cry"): st.cache_data.clear()
    with st.spinner("Fetching crypto..."):
        st.markdown(html_table("CRYPTOCURRENCY MARKETS", CRYPTO, "₿"),
                    unsafe_allow_html=True)

# ── TAB 5: CHART ─────────────────────────────────────────────
with tab5:
    c1, c2, c3 = st.columns([2, 2, 8])
    with c1:
        ticker = st.text_input("Ticker", value="SPY", key="chart_ticker").upper()
    with c2:
        period = st.selectbox("Period", ["1mo","3mo","6mo","1y","2y","5y"],
                              index=2, key="chart_period")
    with c3:
        st.markdown("<br>", unsafe_allow_html=True)
        load = st.button("📊 Load Chart", key="load_chart")
    if load or ticker:
        with st.spinner(f"Building chart for {ticker}..."):
            try:
                fig = build_chart_fig(ticker, period)
                st.plotly_chart(fig, use_container_width=True)
            except Exception as e:
                st.error(f"❌ Error: {e}")

# ── TAB 6: MACRO ─────────────────────────────────────────────
with tab6:
    if st.button("🔄 Refresh", key="ref_macro"): st.cache_data.clear()
    with st.spinner("Building macro dashboard..."):
        fig = build_macro_fig()
        st.pyplot(fig, use_container_width=True)
        plt.close(fig)

# ── TAB 7: NEWS ──────────────────────────────────────────────
with tab7:
    nc1, nc2 = st.columns([2, 10])
    with nc1:
        news_tk = st.text_input("Ticker", value="SPY", key="news_ticker").upper()
    with nc2:
        st.markdown("<br>", unsafe_allow_html=True)
        load_news = st.button("📰 Load News", key="load_news")
    if load_news or news_tk:
        q   = batch_quotes((news_tk,))
        inf = q.get(news_tk, dict(price=0, chg=0, pct=0))
        col = "#00FF41" if inf["chg"] >= 0 else "#FF3333"
        sgn = "▲" if inf["chg"] >= 0 else "▼"
        st.markdown(f"""
        <div style='font-family:monospace;padding:10px 0'>
          <span style='color:#FFD700;font-size:24px;font-weight:bold'>{news_tk}</span>&nbsp;&nbsp;
          <span style='color:{col};font-size:20px'>{fmt_price(inf['price'])} {sgn} {fmt_chg(inf['chg'])} ({inf['pct']:+.2f}%)</span>
        </div>""", unsafe_allow_html=True)
        with st.spinner(f"Loading news for {news_tk}..."):
            news = get_news(news_tk)
            if news:
                rows = ""
                for item in news:
                    try:
                        ct    = item.get("content", {})
                        title = ct.get("title", item.get("title", "No title"))
                        pub   = ct.get("pubDate", "")[:10]
                        prov  = ct.get("provider", {})
                        src   = prov.get("displayName","") if isinstance(prov, dict) else ""
                        rows += (f"<tr style='border-bottom:1px solid #1a1a1a'>"
                                 f"<td style='padding:8px 14px;color:#CCC;font-size:12px;line-height:1.5'>{title}</td>"
                                 f"<td style='padding:8px 14px;white-space:nowrap;font-size:11px'>"
                                 f"<span style='color:#555'>{pub}</span>"
                                 + (f"<span style='color:#FF6600'> | {src}</span>" if src else "")
                                 + "</td></tr>")
                    except: continue
                st.markdown(f"""
                <div style='background:#000;font-family:Courier New,monospace;padding:14px;border:1px solid #FF6600;border-radius:4px'>
                  <table style='width:100%;border-collapse:collapse'>
                    <thead><tr style='border-bottom:2px solid #FF6600'>
                      <th style='color:#FF6600;text-align:left;padding:6px 14px'>HEADLINE</th>
                      <th style='color:#FF6600;text-align:left;padding:6px 14px'>DATE / SOURCE</th>
                    </tr></thead>
                    <tbody>{rows}</tbody>
                  </table>
                </div>""", unsafe_allow_html=True)
            else:
                st.warning("No news available for this ticker.")
